//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHAN()
        {
            this.DONTHUOC = new HashSet<DONTHUOC>();
        }
    
        public int MABENHAN { get; set; }
        public string SUB_ID { get; set; }
        public Nullable<int> MAYSI { get; set; }
        public Nullable<int> MABENHNHAN { get; set; }
        public Nullable<int> MADICHVU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOC { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual YSI YSI { get; set; }
    }
}
