//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONTHUOC
    {
        public int MADONTHUOC { get; set; }
        public string SUB_ID { get; set; }
        public Nullable<int> MABENHAN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual BENHAN BENHAN { get; set; }
    }
}
