//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOA()
        {
            this.YSI = new HashSet<YSI>();
        }
    
        public int MAKHOA { get; set; }
        public string SUB_ID { get; set; }
        public string TENKHOA { get; set; }
        public Nullable<System.DateTime> NGAYTHANHLAP { get; set; }
        public Nullable<int> TRUONGKHOA { get; set; }
        public string PICTURE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YSI> YSI { get; set; }
        public virtual YSI YSI1 { get; set; }
    }
}
