//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYBENHVIENEntities : DbContext
    {
        public QUANLYBENHVIENEntities()
            : base("name=QUANLYBENHVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENHAN> BENHAN { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHAN { get; set; }
        public virtual DbSet<DICHVU> DICHVU { get; set; }
        public virtual DbSet<DONTHUOC> DONTHUOC { get; set; }
        public virtual DbSet<KHOA> KHOA { get; set; }
        public virtual DbSet<LICHKHAM> LICHKHAM { get; set; }
        public virtual DbSet<PHONG> PHONG { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<YSI> YSI { get; set; }
    }
}
