//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string MASO { get; set; }
        public string LOAITAIKHOAN { get; set; }
        public string AVATAR { get; set; }
    }
}
