//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YSI()
        {
            this.BENHAN = new HashSet<BENHAN>();
            this.KHOA1 = new HashSet<KHOA>();
            this.LICHKHAM = new HashSet<LICHKHAM>();
            this.YSI1 = new HashSet<YSI>();
        }
    
        public int MAYSI { get; set; }
        public string SUB_ID { get; set; }
        public Nullable<int> MAKHOA { get; set; }
        public Nullable<int> MAPHONG { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
        public string LOAIYSI { get; set; }
        public Nullable<int> MACHIHUY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENHAN> BENHAN { get; set; }
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOA> KHOA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHKHAM> LICHKHAM { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YSI> YSI1 { get; set; }
        public virtual YSI YSI2 { get; set; }
    }
}
