USE MASTER
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QUANLYBENHVIEN')
BEGIN
	ALTER DATABASE QUANLYBENHVIEN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE QUANLYBENHVIEN;
END
GO
CREATE DATABASE QUANLYBENHVIEN