------------------------PHÒNG------------------------------------------
CREATE TABLE PHONG(
    MAPHONG VARCHAR(10) PRIMARY KEY, 
    SOPHONG tinyint, 
    TANG tinyint,  
    TENPHONG VARCHAR(30), 
    SOLUONGYSI tinyint, 
    SUCCHUA tinyint, 
    SOGIUONGBENH TINYINT
)
GO
--------------------------TÀI SẢN CÔNG----------------------------------------------------------------
CREATE TABLE TAISANCONG(
    MATAISAN VARCHAR(10) PRIMARY KEY, 
    TENTAISAN NVARCHAR(30), 
    LOAITAISAN NVARCHAR(30)
)
GO

---------------------------GIÁ ĐIỀU TRỊ----------------------------------------------------------------
CREATE TABLE GIADIEUTRI(
    MALOAIDIEUTRI VARCHAR(10) PRIMARY KEY, 
    TEN NVARCHAR(30), 
    GIATIEN SMALLMONEY
)

--------------------------THUỐC-----------------------------------------------------------------------
CREATE TABLE THUOC(
    MATHUOC VARCHAR(10) PRIMARY KEY,  
    TENTHUOC NVARCHAR(30), 
    GIATHUOC SMALLMONEY, 
    NHASX NVARCHAR(30)
)
GO

-------------------------GIÁ XÉT NGHIỆM----------------------------------------------------------------
CREATE TABLE GIAXETNGHIEM(
    MALOAIXETNGHIEM VARCHAR(10) PRIMARY KEY, 
    GIA SMALLMONEY
)
GO

--------------------NHÂN VIÊN----------------------------------------------------------------
CREATE TABLE NHANVIEN(
    MANV VARCHAR(10) PRIMARY KEY, 
    TENNV VARCHAR(30), 
    CHUCVU VARCHAR(30),
    NOILAMVIEC VARCHAR(30), 
    NGAYVAOLAM smalldatetime, 
) 

-------------------KHOA----------------------------------------------------------------
CREATE TABLE KHOA(
    MAKHOA VARCHAR(10) PRIMARY KEY,
    TENKHOA NVARCHAR(30), 
    SOLUONG SMALLINT, 
    NGAYTHANHLAP smalldatetime, 
    TRUONGKHOA VARCHAR(10),
)
GO
------------------------Y SI---------------------------------------------
GO
CREATE TABLE YSI (
    MAYSI VARCHAR(10) PRIMARY KEY, 
    MAKHOA VARCHAR(10), 
    TENYSI NVARCHAR(30), 
    NGAYVAOLAM DATETIME, 
    CHUCVU NVARCHAR(20),  
    HESOLUONG NUMERIC(4,2), 
    LOAIYSI NVARCHAR(20), 
    CHIHUY VARCHAR(10),
    CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
)

ALTER TABLE YSI ADD CONSTRAINT FK_CHIHUY FOREIGN KEY (CHIHUY) REFERENCES YSI(MAYSI)
ALTER TABLE KHOA ADD CONSTRAINT FK_TRUONGKHOA FOREIGN KEY (TRUONGKHOA) REFERENCES YSI(MAYSI)
GO

------------------------BENH NHAN----------------------------------------
CREATE TABLE BENHNHAN(
    MABENHNHAN VARCHAR(10) PRIMARY KEY, 
    TENBENHNHAN NVARCHAR(30),
    GIOITINH NVARCHAR(5), 
    MABHYT VARCHAR(20)
)
GO
---------------------DANGKYNOITRU--------------------------------------
CREATE TABLE DANGKYNOITRU(
    MABENHNHAN VARCHAR(10), 
    MAPHONG VARCHAR(10), 
    THOIGIANNHAPVIEN smalldatetime, 
    THOIGIANXUATVIEN smalldatetime,
    CONSTRAINT FK_MABENHNHAN FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN)
)
GO
------------------TUC TRUC-----------------------------------------------
CREATE TABLE TUCTRUC(
    MATRUC VARCHAR(10), 
    MAYSI VARCHAR(10),
    MAPHONG VARCHAR(10), 
    CATRUC SMALLINT,
    CONSTRAINT PK_MATRUC PRIMARY KEY (MATRUC),
    CONSTRAINT FK_MAYSI FOREIGN KEY (MAYSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
)

GO


--------------------LICH KHAM----------------------------------------------------------------
CREATE TABLE LICHKHAM(
    MALICHKHAM VARCHAR(10) PRIMARY KEY,
    MABACSI VARCHAR(10), 
    MABENHNHAN VARCHAR(10),
    MAPHONG VARCHAR(10),
    NGAYKHAM smalldatetime,
    NGAYLENLICH smalldatetime
    CONSTRAINT FK_MABACSI_LICHKHAM FOREIGN KEY (MABACSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_LICHKHAM FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_MAPHONG_LICHKHAM FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
)
GO
-------------------------ĐƠN THUỐC----------------------------------------------------------------
CREATE TABLE DONTHUOC(
    MADONTHUOC VARCHAR(10) PRIMARY KEY, 
    GIATIEN SMALLMONEY,
)
GO

---------------------------------CHI TIẾT ĐƠN THUỐC-----------------------------------------------
CREATE TABLE CHITIETDONTHUOC(
    MADONTHUOC VARCHAR(10), 
    MATHUOC VARCHAR(10),
    CONSTRAINT PK_MADONTHUOC_CTDT PRIMARY KEY(MADONTHUOC, MATHUOC),
    CONSTRAINT FK_MADONTHUOC_CTDT FOREIGN KEY (MADONTHUOC) REFERENCES DONTHUOC(MADONTHUOC),
    CONSTRAINT FK_MATHUOC_CTDT FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC)
)
GO

-------------------------------ĐIỀU TRỊ---------------------------------------------------------
CREATE TABLE DIEUTRI(
    MADIEUTRI VARCHAR(10) PRIMARY KEY, 
    MAYSI VARCHAR(10), 
    MABENHNHAN VARCHAR(10), 
    MADONTHUOC VARCHAR(10), 
    LOAIDIEUTRI VARCHAR(10), 
    THANHTIEN SMALLMONEY,
    CONSTRAINT FK_MAYSI_DIEUTRI FOREIGN KEY (MAYSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_DIEUTRI FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_MADONTHUOC_DIEUTRI FOREIGN KEY (MADONTHUOC) REFERENCES DONTHUOC(MADONTHUOC),
    CONSTRAINT FK_LOAIDIEUTRI_DIEUTRI FOREIGN KEY (LOAIDIEUTRI) REFERENCES GIADIEUTRI(MALOAIDIEUTRI),
    )

GO
--------------------------XÉT NGHIỆM----------------------------------------------------------------

CREATE TABLE XETNGHIEM(
    MAXETNGHIEM VARCHAR(10) PRIMARY KEY, 
    MADIEUTRI VARCHAR(10), 
    LOAIXETNGHIEM VARCHAR(10), 
    GIOXETNGHIEM smalldatetime,
    CONSTRAINT FK_MADIEUTRI_XETNGHIEM FOREIGN KEY (MADIEUTRI) REFERENCES DIEUTRI(MADIEUTRI),
    CONSTRAINT FK_LOAIXETNGHIEM_XETNGHIEM FOREIGN KEY (LOAIXETNGHIEM) REFERENCES GIAXETNGHIEM(MALOAIXETNGHIEM)
)
GO
------------------------------TÀI KHOẢN NHÂN VIÊN KỸ THUẬT------------------------------------------------------
CREATE TABLE TAIKHOANNHANVIENKYTHUAT(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(20), 
    MASO VARCHAR(10)
    CONSTRAINT FK_MASO_ACCNVKT FOREIGN KEY (MASO) REFERENCES NHANVIEN(MANV)
)
GO
------------------------------TÀI KHOẢN LỄ TÂN------------------------------------------------------
CREATE TABLE TAIKHOANLETAN(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(20), 
    MASO VARCHAR(10)
    CONSTRAINT FK_MASO_ACCLT FOREIGN KEY (MASO) REFERENCES NHANVIEN(MANV)
)
 

GO

------------------------------TÀI KHOẢN NHÂN VIÊN GIÁM ĐỐC------------------------------------------------------
CREATE TABLE TAIKHOANGIAMDOC(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(20), 
    MASO VARCHAR(10)
    CONSTRAINT FK_MASO_ACCGD FOREIGN KEY (MASO) REFERENCES NHANVIEN(MANV)
)
GO

------------------------------TÀI KHOẢN TRƯỞNG KHOA------------------------------------------------------
CREATE TABLE TAIKHOANTRUONGKHOA(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(20), 
    MASO VARCHAR(10)
    CONSTRAINT FK_MASO_ACCTK FOREIGN KEY (MASO) REFERENCES YSI(MAYSI)
)
GO

-----------------------------NHÂN VIÊN SỬ DỤNG TÀI SẢN--------------------------------------------------
CREATE TABLE NHANVIENSUDUNGTAISAN(
    MANHANVIEN VARCHAR(10), 
    MATAISAN VARCHAR(10), 
    NGAYSUDUNG smalldatetime, 
    NGAYKETTHUC smalldatetime, 
    MUCDICH NVARCHAR(50),
    CONSTRAINT PK_MANV_MATAISAN PRIMARY KEY (MANHANVIEN, MATAISAN),
    CONSTRAINT FK_MANHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_MATAISAN FOREIGN KEY (MATAISAN) REFERENCES TAISANCONG(MATAISAN)
)
GO

------------------------------BỆNH NHÂN SỬ DỤNG TÀI SẢN-------------------------------------------------
CREATE TABLE BENHNHANSUDUNGTAISAN(
    MAGIUONGG VARCHAR(10) PRIMARY KEY, 
    MABENHNHAN VARCHAR(10), 
    NGAYSUDUNG smalldatetime, 
    NGAYKETTHUC smalldatetime, 
    MUCDICH NVARCHAR(50),
    CONSTRAINT FK_MAGIUONG_BNDUNGTS FOREIGN KEY (MAGIUONGG) REFERENCES TAISANCONG(MATAISAN),
    CONSTRAINT FK_MABENHNHAN_BNDUNGTS FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN)
)

