USE QUANLYBENHVIEN

------------------------PHÒNG------------------------------------------
CREATE TABLE PHONG(
    MAPHONG INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'PHG' + CAST(MAPHONG AS VARCHAR(10)),
    TANG tinyint,  
    TENPHONG NVARCHAR(30), 
    SUCCHUA tinyint, 
)
GO

-------------------KHOA----------------------------------------------------------------
CREATE TABLE KHOA(
    MAKHOA INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'K' + CAST(MAKHOA AS VARCHAR(10)),
    TENKHOA NVARCHAR(30), 
    NGAYTHANHLAP smalldatetime, 
    TRUONGKHOA INT,
    PICTURE VARCHAR(50),
)
GO
------------------------Y SI---------------------------------------------
GO
CREATE TABLE YSI (
    MAYSI INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'M' + CAST(MAYSI AS VARCHAR(10)),
    MAKHOA INT, 
    MAPHONG INT,
    HOTEN NVARCHAR(30), 
    GIOITINH NVARCHAR(5),
    NGAYSINH DATETIME,
    NGAYVAOLAM DATETIME, 
    LOAIYSI NVARCHAR(20), 
    MACHIHUY INT,
    CONSTRAINT FK_MAKHOA_YSI FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
    CONSTRAINT FK_MAPHONG_YSI FOREIGN KEY (MAPHONG) REFERENCES PHONG (MAPHONG)
)

ALTER TABLE YSI ADD CONSTRAINT FK_CHIHUY_YSI FOREIGN KEY (MACHIHUY) REFERENCES YSI(MAYSI)
ALTER TABLE KHOA ADD CONSTRAINT FK_TRUONGKHOA FOREIGN KEY (TRUONGKHOA) REFERENCES YSI(MAYSI)
GO

USE QUANLYBENHVIEN
------------------------BENH NHAN----------------------------------------
CREATE TABLE BENHNHAN(
    MABENHNHAN INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'BN' + CAST(MABENHNHAN AS VARCHAR(10)),
    MAPHONG INT,
    HOTEN NVARCHAR(30),
    GIOITINH NVARCHAR(5), 
    NGAYSINH DATETIME,
    DIACHI NVARCHAR (30),
    MABHYT VARCHAR(20),
    NGAYNHAPVIEN DATETIME,
    CONSTRAINT FK_MAPHONG_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
)
GO

-------------------------------DỊCH VỤ---------------------------------------------------------
CREATE TABLE DICHVU(
    MADICHVU INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'DV' + CAST(MADICHVU AS VARCHAR(10)),
    TENDICHVU NVARCHAR(30),
    GIATIEN MONEY,
    PICTURE VARCHAR(50),
)
GO
--------------------LICH KHAM----------------------------------------------------------------
CREATE TABLE LICHKHAM(
    MALICHKHAM INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'LK' + CAST(MALICHKHAM AS VARCHAR(10)),
    MABACSI INT, 
    MABENHNHAN INT,
    MAPHONG INT,
    MADICHVU INT,
    NGAYKHAM smalldatetime,
    NGAYLENLICH smalldatetime
    CONSTRAINT FK_MABACSI_LICHKHAM FOREIGN KEY (MABACSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_LICHKHAM FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_MAPHONG_LICHKHAM FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_MADICHVU_LICHKHAM FOREIGN KEY (MADICHVU) REFERENCES DICHVU(MADICHVU)
)


-------------------------------BỆNH ÁN---------------------------------------------------------
CREATE TABLE BENHAN(
    MABENHAN INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'BA' + CAST(MABENHAN AS VARCHAR(10)),
    MAYSI INT, 
    MABENHNHAN INT, 
    MADICHVU INT, 
    GHICHU VARCHAR(MAX),
    THANHTIEN MONEY,
    CONSTRAINT FK_MAYSI_BENHAN FOREIGN KEY (MAYSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_BENHAN FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_DICHVU_BENHAN FOREIGN KEY (MADICHVU) REFERENCES DICHVU(MADICHVU),
    )
-------------------------ĐƠN THUỐC----------------------------------------------------------------
CREATE TABLE DONTHUOC(
    MADONTHUOC INT IDENTITY(1,1) PRIMARY KEY, 
    SUB_ID AS 'DT' + CAST(MADONTHUOC AS VARCHAR(10)),
    MABENHAN INT,
    GHICHU VARCHAR(MAX),
    CONSTRAINT FK_BENHAN_DONTHUOC FOREIGN KEY (MABENHAN) REFERENCES BENHAN(MABENHAN),
)
GO


------------------------------TÀI KHOẢN------------------------------------------------------
CREATE TABLE TAIKHOAN(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(70),
    MASO VARCHAR(20),
    LOAITAIKHOAN NVARCHAR(10),
    AVATAR VARCHAR(50),
)
 

GO



-- TÀI KHOẢN CONSTRANT ----
ALTER TABLE TAIKHOAN 
ADD CONSTRAINT LOAITAIKHOAN_CONSTRAINT 
CHECK (LOAITAIKHOAN IN (N'Bác sĩ', N'Tiếp tân', N'Hội đồng quản trị', 'Admin'))

-- PHÒNG CONSTAINT ----
ALTER TABLE PHONG
ADD CONSTRAINT PHONG_TANG_CONSTRAINT
CHECK (TANG >= 0);
ALTER TABLE PHONG
ADD CONSTRAINT PHONG_SUCCHUACONSTRAINT
CHECK (SUCCHUA >= 0);

-- KHOA CONSTRAINT ---



--- Y SI CONSTRAINT ---
ALTER TABLE YSI
ADD CONSTRAINT YSI_GIOITINH_CONSTRAINT
CHECK (GIOITINH IN (N'Nam', N'Nữ'))

ALTER TABLE YSI
ADD CONSTRAINT YSI_NGAYSINH_NGAYVAOLAM_CONSTRAINT
CHECK (NGAYSINH <= NGAYVAOLAM)

--- BENH NHAN CONSTRAINT ----
ALTER TABLE BENHNHAN
ADD CONSTRAINT BENHNHAN_GIOITINH_CONSTRAINT
CHECK (GIOITINH IN (N'Nam', N'Nữ'))

ALTER TABLE BENHNHAN
ADD CONSTRAINT BENHNHAN_NGAYSINH_NGAYNHAPVIEN_CONSTRAINT
CHECK (NGAYSINH < NGAYNHAPVIEN)


--- DICH VU CONSTRAINT ---



--- LICHKHAM CONSTRAINT ---
ALTER TABLE LICHKHAM
ADD CONSTRAINT BENHNHAN_NGAYKHAM_NGAYLENLICH_CONSTRAINT
CHECK (NGAYLENLICH <= NGAYKHAM)

--- BENH AN CONSTRAINT ---


--- DON THUOC CONSTRAINT ---


---Sửa---


---Lịch khám---
ALTER TABLE BENHAN
ADD TRIEUCHUNG NVARCHAR(MAX);

ALTER TABLE BENHAN
ADD NGAYKHAM smalldatetime;

ALTER TABLE BENHAN
ADD KETLUAN NVARCHAR(MAX);

ALTER TABLE BENHAN
DROP COLUMN GHICHU;


--- Đơn thuốc ---
ALTER TABLE DONTHUOC
ALTER COLUMN GHICHU NVARCHAR(MAX);
