USE QUANLYBENHVIEN

------------------------PHÒNG------------------------------------------
CREATE TABLE PHONG(
    MAPHONG VARCHAR(10) PRIMARY KEY, 
    TANG tinyint,  
    TENPHONG VARCHAR(30), 
    SUCCHUA tinyint, 
)
GO

-------------------KHOA----------------------------------------------------------------
CREATE TABLE KHOA(
    MAKHOA VARCHAR(10) PRIMARY KEY,
    TENKHOA NVARCHAR(30), 
    NGAYTHANHLAP smalldatetime, 
    TRUONGKHOA VARCHAR(10),
)
GO
------------------------Y SI---------------------------------------------
GO
CREATE TABLE YSI (
    MAYSI VARCHAR(10) PRIMARY KEY, 
    MAKHOA VARCHAR(10), 
    MAPHONG VARCHAR(10),
    HOTEN NVARCHAR(30), 
    GIOITINH NVARCHAR(5),
    NGAYSINH DATETIME,
    NGAYVAOLAM DATETIME, 
    LOAIYSI NVARCHAR(20), 
    MACHIHUY VARCHAR(10),
    CONSTRAINT FK_MAKHOA_YSI FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
    CONSTRAINT FK_MAPHONG_YSI FOREIGN KEY (MAPHONG) REFERENCES PHONG (MAPHONG)
)

ALTER TABLE YSI ADD CONSTRAINT FK_CHIHUY_YSI FOREIGN KEY (MACHIHUY) REFERENCES YSI(MAYSI)
ALTER TABLE KHOA ADD CONSTRAINT FK_TRUONGKHOA FOREIGN KEY (TRUONGKHOA) REFERENCES YSI(MAYSI)
GO

------------------------BENH NHAN----------------------------------------
CREATE TABLE BENHNHAN(
    MABENHNHAN VARCHAR(10) PRIMARY KEY, 
    MAPHONG VARCHAR(10),
    HOTEN NVARCHAR(30),
    GIOITINH NVARCHAR(5), 
    NGAYSINH DATETIME,
    DIACHI NVARCHAR (30),
    MABHYT VARCHAR(20),
    NGAYNHAPVIEN DATETIME,
    CONSTRAINT FK_MAPHONG_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
)
GO
GO
-------------------------------DỊCH VỤ---------------------------------------------------------
CREATE TABLE DICHVU(
    MADICHVU VARCHAR(10) PRIMARY KEY,
    TENDICHVU NVARCHAR(30),
    GIATIEN MONEY
)
GO
--------------------LICH KHAM----------------------------------------------------------------
CREATE TABLE LICHKHAM(
    MALICHKHAM VARCHAR(10) PRIMARY KEY,
    MABACSI VARCHAR(10), 
    MABENHNHAN VARCHAR(10),
    MAPHONG VARCHAR(10),
    MADICHVU VARCHAR(10),
    NGAYKHAM smalldatetime,
    NGAYLENLICH smalldatetime
    CONSTRAINT FK_MABACSI_LICHKHAM FOREIGN KEY (MABACSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_LICHKHAM FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_MAPHONG_LICHKHAM FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_MADICHVU_LICHKHAM FOREIGN KEY (MADICHVU) REFERENCES DICHVU(MADICHVU)
)


-------------------------------BỆNH ÁN---------------------------------------------------------
CREATE TABLE BENHAN(
    MABENHAN VARCHAR(10) PRIMARY KEY, 
    MAYSI VARCHAR(10), 
    MABENHNHAN VARCHAR(10), 
    MADICHVU VARCHAR(10), 
    GHICHU VARCHAR(MAX),
    THANHTIEN MONEY,
    CONSTRAINT FK_MAYSI_BENHAN FOREIGN KEY (MAYSI) REFERENCES YSI(MAYSI),
    CONSTRAINT FK_MABENHNHAN_BENHAN FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT FK_DICHVU_BENHAN FOREIGN KEY (MADICHVU) REFERENCES DICHVU(MADICHVU),
    )
-------------------------ĐƠN THUỐC----------------------------------------------------------------
CREATE TABLE DONTHUOC(
    MADONTHUOC VARCHAR(10) PRIMARY KEY, 
    MABENHAN VARCHAR(10),
    GHICHU VARCHAR(MAX),
    CONSTRAINT FK_BENHAN_DONTHUOC FOREIGN KEY (MABENHAN) REFERENCES BENHAN(MABENHAN),
)
GO


------------------------------TÀI KHOẢN------------------------------------------------------
CREATE TABLE TAIKHOAN(
    TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
    MATKHAU VARCHAR(70),
    MASO VARCHAR(20),
    LOAITAIKHOAN VARCHAR(10)
)
 

GO

-- ------------------------------TÀI KHOẢN NHÂN VIÊN GIÁM ĐỐC------------------------------------------------------
-- CREATE TABLE TAIKHOANGIAMDOC(
--     TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
--     MATKHAU VARCHAR(20), 
-- )
-- GO

-- ------------------------------TÀI KHOẢN TRƯỞNG KHOA------------------------------------------------------
-- CREATE TABLE TAIKHOANTRUONGKHOA(
--     TENDANGNHAP VARCHAR(30) PRIMARY KEY, 
--     MATKHAU VARCHAR(20), 
--     MASO VARCHAR(10)
--     CONSTRAINT FK_MASO_ACCTK FOREIGN KEY (MASO) REFERENCES YSI(MAYSI)
-- )
-- GO

